baseURL = 'https://internetguy.dev/'
languageCode = 'en-us'
title = 's1mplicity'
theme = 'github-style'

[params]
  author = "s1mplicity"
  description = "ctfs | research team | students"
  favicon = "/images/1.png"
  avatar = "/images/1.png"
  headerIcon = "/images/2.png"
  location = "America/New_York"
  url = "https://s1mplicity.internetguy.dev"
  enableSearch = true